# Generated by Django 4.0.4 on 2022-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='foto',
            field=models.ImageField(blank=True, default='static/images/rojoes.jpeg', null=True, upload_to='static/images'),
        ),
    ]
