# Generated by Django 4.0.4 on 2022-04-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas_app', '0003_alter_receitas_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='foto',
            field=models.ImageField(blank=True, default='download_pr2ep5.jpg', null=True, upload_to=''),
        ),
    ]
