# Generated by Django 4.0.4 on 2022-04-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas_app', '0004_alter_receitas_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='ingrediente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='unidade',
            field=models.CharField(blank=True, default='g', max_length=100),
        ),
        migrations.AlterField(
            model_name='quantidadeingredientes',
            name='quantidade',
            field=models.FloatField(default=1),
        ),
    ]
